version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: notes_db
    restart: always
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  note-api:
    build: .
    container_name: note-api
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: nest
      DB_PASS: nest
      DB_NAME: notesdb
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  pgdata:
